$ErrorActionPreference = "Stop"

# Detect APPROOT (.\app or .\src\app)
$APPROOT = ""
if (Test-Path ".\src\app") { $APPROOT = ".\src\app" }
elseif (Test-Path ".\app") { $APPROOT = ".\app" }
else { throw "ERROR: neither .\src\app nor .\app exists." }

Write-Host ("OK: APPROOT = " + $APPROOT) -ForegroundColor Green

function WriteBytesFromB64([string]$filePath, [string]$b64) {
  $dir = Split-Path $filePath -Parent
  if ($dir -and !(Test-Path $dir)) { New-Item -ItemType Directory -Force -Path $dir | Out-Null }
  $clean = ($b64 -replace '\s','')
  [System.IO.File]::WriteAllBytes($filePath, [Convert]::FromBase64String($clean))
}

# Valid PNG 32x32 (transparent)
$pngB64 = @"
iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAAGklEQVR4nO3B
AQEAAACCIP+vbkhAAQAAAO8GECAAARlDNO4AAAAASUVORK5CYII=
"@

# Valid ICO 16x16 (transparent)
$icoB64 = @"
AAABAAEAEBAAAAAAIABPAAAAFgAAACgAAAAQAAAAIAAAAAEAGAAAAAAAQAEAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP8AAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAP8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP8AAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAP8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP8AAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAP8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==
"@

# Backup old files (if any)
$iconPng = Join-Path $APPROOT "icon.png"
$favIco  = Join-Path $APPROOT "favicon.ico"

if (Test-Path $iconPng) { Copy-Item $iconPng ($iconPng + ".bak") -Force }
if (Test-Path $favIco)  { Copy-Item $favIco  ($favIco  + ".bak") -Force }

# Write new valid files
WriteBytesFromB64 $iconPng $pngB64
WriteBytesFromB64 $favIco  $icoB64

Write-Host "OK: icon.png + favicon.ico replaced with valid files" -ForegroundColor Green
Get-Item $iconPng | Select-Object FullName, Length
Get-Item $favIco  | Select-Object FullName, Length
